name: MegaBytesPerPie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#403732'
    - '#CFD0D7'
    - '#C7E04B'
    - '#898681'
    - '#9A2016'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
