layout_spectrum: 0.9928315
color:
  saturation: 0.7057906
  lightness: 0.8622041
  brandStrength: 0.5065781
  brandColors:
    - '#403732'
    - '#CFD0D7'
    - '#C7E04B'
    - '#898681'
    - '#9A2016'
  rhythmicContrast: 0.08444332
typography_spectrum: 0.1397849
name: MegaBytesPerPie
